config/routes.rb
Smdb::Application.routes.draw do
  root "movies#index"

  get '/signin' => 'sessions#new', :as => 'sign_in'
  post '/sessions/create' => 'sessions#create'
  delete '/signout' => 'sessions#destroy', :as => 'sign_out'

  resources :votes

  resources :users

  resources :roles

  resources :actors

  resources :movies

  resources :directors

end

app/models/director.rb
class Director < ActiveRecord::Base
  has_many :movies
  # def movies
  #   Movie.where(:director_id => self.id)
  # end

  validates :name, :uniqueness => true
  validates :name, :dob, :presence => true
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: [:show, :edit, :update, :destroy]

  # GET /directors
  # GET /directors.json
  def index
    @directors = Director.all
  end

  # GET /directors/1
  # GET /directors/1.json
  def show
  end

  # GET /directors/new
  def new
    @director = Director.new
  end

  # GET /directors/1/edit
  def edit
  end

  # POST /directors
  # POST /directors.json
  def create
    @director = Director.new(director_params)

    respond_to do |format|
      if @director.save
        format.html { redirect_to @director, notice: 'Director was successfully created.' }
        format.json { render action: 'show', status: :created, location: @director }
      else
        format.html { render action: 'new' }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directors/1
  # PATCH/PUT /directors/1.json
  def update
    respond_to do |format|
      if @director.update(director_params)
        format.html { redirect_to @director, notice: 'Director was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directors/1
  # DELETE /directors/1.json
  def destroy
    @director.destroy
    respond_to do |format|
      format.html { redirect_to directors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_director
      @director = Director.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def director_params
      params.require(:director).permit(:name, :dob)
    end
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/views/directors/_form.html.erb
<%= form_for(@director) do |f| %>
  <% if @director.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@director.errors.count, "error") %> prohibited this director from being saved:</h2>

      <ul>
      <% @director.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.date_select :dob %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/directors/edit.html.erb
<h1>Editing director</h1>

<%= render 'form' %>

<%= link_to 'Show', @director %> |
<%= link_to 'Back', directors_path %>

app/views/directors/index.html.erb
<h1>Listing directors</h1>

<table class="table content-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Dob</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @directors.each do |director| %>
      <tr>
        <td><%= director.name %></td>
        <td><%= director.dob %></td>
        <td><%= link_to 'Show', director, :class => 'btn btn-default btn-small' %></td>
        <td><%= link_to 'Edit', edit_director_path(director), :class => 'btn btn-warning btn-small' %></td>
        <td><%= link_to 'Destroy', director, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-small' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Director', new_director_path, :class => 'btn btn-primary btn-large' %>

app/views/directors/new.html.erb
<h1>New director</h1>

<%= render 'form' %>

<%= link_to 'Back', directors_path %>

app/views/directors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @director.name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @director.dob %>
</p>

<p>Movies:</p>

<ul>
  <% @director.movies.each do |movie| %>
    <li><%= movie.title %></li>
  <% end %>
</ul>



<%= link_to 'Edit', edit_director_path(@director) %> |
<%= link_to 'Back', directors_path %>