config/routes.rb
Smdb::Application.routes.draw do
  root "movies#index"

  get '/signin' => 'sessions#new', :as => 'sign_in'
  post '/sessions/create' => 'sessions#create'
  delete '/signout' => 'sessions#destroy', :as => 'sign_out'

  resources :votes

  resources :users

  resources :roles

  resources :actors

  resources :movies

  resources :directors

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smdb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

      <div class="navbar">
        <div class="container">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "SMDB", root_url, :class => 'navbar-brand'  %>
          <div class="nav-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "Movies", movies_url  %></li>
              <li><%= link_to "Directors", directors_url  %></li>
              <li><%= link_to "Actors", actors_url  %></li>
              <li><%= link_to "Roles", roles_url  %></li>
              <li><%= link_to "Users", users_url  %></li>
              <li><%= link_to "Votes", votes_url  %></li>
            </ul>
            <% u = User.find_by_id(session[:user_id]) %>
            <% if session[:user_id] %>
              <ul class="nav navbar-nav pull-right">
                <li><%= link_to "sign out", sign_out_url, method: 'delete' %></li>
              </ul>
              <p class="navbar-text pull-right">Signed in as <a href="/users/<%= session[:user_id] %>" class="navbar-link"><%= u.name %></a></p>
            <% else %>
              <ul class="nav navbar-nav pull-right">
                <li><%= link_to "sign in", sign_in_url  %></li>
                <li><%= link_to "sign up", new_user_url  %></li>
              </ul>
            <% end %>
          </div><!-- /.nav-collapse -->
        </div><!-- /.container -->
      </div><!-- /.navbar -->

<!-- add a navbar here -->

<div class="container">
  <%= yield %>
</div>

</body>
</html>